apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        environment: test
    name: nginix-deployment
spec:
  replicas: 3
  strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      environment: test
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
        